"use client";
import { useState } from "react";
import type { AdminCustomerDetail } from "@/lib/services/admin-customers-service";

type Tab = "overview" | "orders" | "loyalty" | "rma" | "addresses" | "notes";
const money = (c:number) => new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(c/100);
const dec = (v:string|null|undefined) => new Intl.NumberFormat("pt-PT",{style:"currency",currency:"EUR"}).format(Number(v||0));
const date = (v:Date|string|null|undefined) => v ? new Date(v).toLocaleDateString("pt-PT") : "—";

export default function Customer360Detail({detail,saving,noteText,setNoteText,onClose,onAddNote,onDeleteNote,onToggleStatus}:{
 detail:AdminCustomerDetail;saving:boolean;noteText:string;setNoteText:(v:string)=>void;onClose:()=>void;onAddNote:()=>void;onDeleteNote:(id:number)=>void;onToggleStatus:(a:"disable"|"reactivate")=>void;
}) {
 const [tab,setTab]=useState<Tab>("overview");
 const tabs:Array<[Tab,string]>=[["overview","Visão geral"],["orders",`Encomendas (${detail.ordersPaginated.pagination.total})`],["loyalty","Fidelização"],["rma",`RMA (${detail.rmaSummary.total})`],["addresses",`Moradas (${detail.addresses.length})`],["notes",`Notas (${detail.notes.length})`]];
 return <div className="mt-6 bg-white border rounded-xl overflow-hidden">
  <div className="p-6 border-b flex justify-between gap-3"><div><p className="text-xs uppercase text-slate-400">Customer360</p><h3 className="text-xl font-bold">{detail.customer.name}</h3><p className="text-sm text-slate-500">{detail.customer.email}</p></div><button onClick={onClose}>Fechar</button></div>
  <div className="p-6">
   <div className="grid md:grid-cols-2 lg:grid-cols-5 gap-3 mb-6">{[["Encomendas",String(detail.statistics.totalOrders)],["Total gasto",money(detail.statistics.totalSpentCents)],["Ticket médio",money(detail.statistics.averageOrderValueCents)],["Saldo",`${detail.loyalty.balancePoints} pts`],["Disponível",money(detail.loyalty.redemptionValueCents)]].map(([l,v])=><div key={l} className="bg-slate-50 rounded p-3"><b>{v}</b><p className="text-xs text-slate-500">{l}</p></div>)}</div>
   <div className="flex gap-2 overflow-x-auto border-b mb-6">{tabs.map(([k,l])=><button key={k} onClick={()=>setTab(k)} className={`px-3 py-2 text-sm whitespace-nowrap border-b-2 ${tab===k?"border-sky-600 text-sky-700 font-semibold":"border-transparent text-slate-500"}`}>{l}</button>)}</div>

   {tab==="overview"&&<div className="grid lg:grid-cols-3 gap-4 text-sm">
    <section className="border rounded p-4"><h4 className="font-semibold mb-2">Cliente</h4><p><b>Email:</b> {detail.customer.email}</p><p><b>Telefone:</b> {detail.customer.phone||"—"}</p><p><b>NIF:</b> {detail.customer.nif||"—"}</p><p><b>Empresa:</b> {detail.customer.company||"—"}</p><p><b>Registo:</b> {date(detail.customer.createdAt)}</p></section>
    <section className="border rounded p-4"><h4 className="font-semibold mb-2">Atividade</h4><p><b>Última encomenda:</b> {date(detail.statistics.lastOrderDate)}</p><p><b>RMA:</b> {detail.rmaSummary.total} ({detail.rmaSummary.open} abertos)</p><p><b>Wishlist:</b> {detail.wishlistCount}</p><p><b>Notas:</b> {detail.notes.length}</p></section>
    <section className="border rounded p-4"><h4 className="font-semibold mb-2">Conta</h4><p className="text-xs text-slate-500 mb-3">{detail.customer.isActive?"Ativa":"Desativada"}</p><button disabled={saving} onClick={()=>onToggleStatus(detail.customer.isActive?"disable":"reactivate")} className={`px-3 py-2 text-white rounded text-xs ${detail.customer.isActive?"bg-red-500":"bg-green-600"}`}>{detail.customer.isActive?"Desativar conta":"Reativar conta"}</button></section>
   </div>}

   {tab==="orders"&&<div className="overflow-x-auto">{detail.ordersPaginated.orders.length===0?<p className="text-sm text-slate-400">Sem encomendas.</p>:<table className="w-full text-xs min-w-[1050px]"><thead className="bg-slate-50"><tr><th className="p-2 text-left">Encomenda</th><th className="p-2 text-right">Valores</th><th className="p-2 text-left">Fidelização</th><th className="p-2 text-left">Pagamento</th><th className="p-2 text-left">Fatura</th><th className="p-2 text-left">Transporte</th><th className="p-2 text-left">Estado</th></tr></thead><tbody>{detail.ordersPaginated.orders.map(o=><tr key={o.id} className="border-t align-top"><td className="p-2"><b>#{o.orderNumber}</b><br/>{date(o.createdAt)} · {o.itemCount} artigo(s)</td><td className="p-2 text-right">Subtotal {dec(o.subtotal)}<br/>Desconto {dec(o.discount)}<br/><b>Total {dec(o.total)}</b>{o.refundedCents>0&&<><br/>Reemb. {money(o.refundedCents)}</>}</td><td className="p-2">{Number(o.loyaltyDiscount)>0?<>{o.loyaltyType==="voucher"?"Vale":"Pontos"} · {dec(o.loyaltyDiscount)}{o.loyaltyPoints?<><br/>{o.loyaltyPoints} pts</>:null}</>:"—"}{Number(o.couponDiscount)>0&&<><br/>Cupão · {dec(o.couponDiscount)}</>}</td><td className="p-2">{o.paymentStatus}{o.paymentMethod?` · ${o.paymentMethod}`:""}{o.paymentProvider?<><br/>{o.paymentProvider}</>:null}{o.paymentPaidAt?<><br/>{date(o.paymentPaidAt)}</>:null}</td><td className="p-2">{o.invoiceNumber||"—"}{o.invoiceStatus?<><br/>{o.invoiceStatus}</>:null}</td><td className="p-2">{o.deliveryType==="pickup"?"Levantamento":(o.carrier||o.shippingMethod||"Envio")}{o.trackingNumber?<><br/>{o.trackingNumber}</>:null}</td><td className="p-2">{o.status}{o.shipmentStatus?<><br/>Envio: {o.shipmentStatus}</>:null}</td></tr>)}</tbody></table>}</div>}

   {tab==="loyalty"&&<div className="space-y-6">
    <div className="grid sm:grid-cols-4 gap-2 text-sm">{[["Saldo",detail.loyalty.balancePoints],["Ganhos",detail.loyalty.earnedPoints],["Utilizados",detail.loyalty.redeemedPoints],["Revertidos",detail.loyalty.reversedPoints]].map(([l,v])=><div key={l} className="border rounded p-3"><b>{v}</b><p className="text-slate-500">{l}</p></div>)}</div>
    <section><h4 className="font-semibold text-sm mb-2">Vales ({detail.loyaltyVouchers.length})</h4>{detail.loyaltyVouchers.length===0?<p className="text-xs text-slate-400">Sem vales.</p>:<div className="grid md:grid-cols-2 gap-2">{detail.loyaltyVouchers.map(v=><div key={v.id} className="border rounded p-3 text-xs"><div className="flex justify-between"><b className="font-mono">{v.code}</b><span>{v.status}</span></div><p>{v.points} pts · {money(v.valueCents)}</p><p className="text-slate-400">{date(v.createdAt)}{v.reservedOrderNumber?` · reservado #${v.reservedOrderNumber}`:""}{v.usedOrderNumber?` · usado #${v.usedOrderNumber}`:""}</p></div>)}</div>}</section>
    <section><h4 className="font-semibold text-sm mb-2">Reservas diretas ({detail.loyaltyPointReservations.length})</h4>{detail.loyaltyPointReservations.map(r=><div key={r.id} className="border rounded p-3 text-xs mb-2 flex justify-between"><span>#{r.orderNumber||r.orderId} · {r.points} pts · {money(r.valueCents)}</span><span>{r.status}</span></div>)}</section>
    <section><h4 className="font-semibold text-sm mb-2">Histórico ({detail.loyaltyMovements.length})</h4><div className="border rounded divide-y">{detail.loyaltyMovements.map(m=><div key={m.id} className="p-3 text-xs flex justify-between"><div><b>{m.reason||m.type}</b><p className="text-slate-400">{date(m.createdAt)}{m.orderNumber?` · #${m.orderNumber}`:""}</p></div><b className={m.pointsDelta>0?"text-green-600":"text-red-600"}>{m.pointsDelta>0?"+":""}{m.pointsDelta}</b></div>)}</div></section>
   </div>}

   {tab==="rma"&&<div className="space-y-2">{detail.rmaRequests.length===0?<p className="text-sm text-slate-400">Sem pedidos RMA.</p>:detail.rmaRequests.map(r=><div key={r.id} className="border rounded p-4 text-sm"><div className="flex justify-between"><b>RMA #{r.id} · {r.type}</b><span>{r.status}</span></div><p>{r.reason||r.description}</p>{r.resolution&&<p className="text-xs mt-2"><b>Resolução:</b> {r.resolution}</p>}</div>)}</div>}

   {tab==="addresses"&&<div><p className="text-sm mb-3"><b>Wishlist:</b> {detail.wishlistCount} produto(s)</p><div className="grid sm:grid-cols-2 gap-2">{detail.addresses.map(a=><div key={a.id} className="border rounded p-3 text-xs"><b>{a.label||a.name}</b><p>{a.address1}{a.address2?`, ${a.address2}`:""}</p><p>{a.postalCode} {a.city} · {a.country}</p><p>{a.isDefaultBilling?"Faturação padrão ":""}{a.isDefaultShipping?"Envio padrão":""}</p></div>)}</div></div>}

   {tab==="notes"&&<div><div className="flex gap-2 mb-3"><input value={noteText} onChange={e=>setNoteText(e.target.value)} maxLength={5000} placeholder="Nova nota interna..." className="border rounded px-3 py-2 text-sm flex-1"/><button onClick={onAddNote} disabled={saving||!noteText.trim()} className="px-3 py-2 bg-sky-600 text-white rounded text-xs">Adicionar</button></div>{detail.notes.map(n=><div key={n.id} className="border-t py-3 text-xs flex justify-between"><div><p>{n.note}</p><p className="text-slate-400">{n.authorName||n.authorEmail||"Sistema"} · {date(n.createdAt)}</p></div><button onClick={()=>onDeleteNote(n.id)} disabled={saving} className="text-red-500">Apagar</button></div>)}</div>}
  </div>
 </div>;
}
