"use client";
import { useCallback, useEffect, useState } from "react";

type Props = { productId: number; onChanged?: () => void | Promise<void> };
type ApplyPart = "description" | "shortDescription" | "attributes";
export default function ProductCatalogEnrichment({ productId, onChanged }: Props) {
  const [data,setData]=useState<any>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState<ApplyPart|null>(null); const [discovering,setDiscovering]=useState(false);
  const load=useCallback(async()=>{ setError(""); const r=await fetch(`/api/admin/products/${productId}/catalog-enrichment`,{cache:"no-store"}); const b=await r.json(); if(!r.ok){setError(b.error||"Erro");return;} setData(b); },[productId]);
  useEffect(()=>{void load();},[load]);
  const latest=data?.snapshots?.slice().sort((a:any,b:any)=>b.id-a.id)[0];
  const discover=async()=>{ const supplierId=data?.links?.[0]?.supplierId; if(!supplierId)return; setDiscovering(true); setError(""); setNotice(""); const r=await fetch("/api/admin/catalog-enrichment/discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"run",supplierId,provider:"upcitemdb",limit:10})}); const b=await r.json(); if(!r.ok)setError(b.error||"Erro na pesquisa"); else setNotice(`Pesquisa concluída: ${b.processed} produto(s) verificados; ${b.results?.filter((x:any)=>x.status==="found").length||0} encontrado(s).`); setDiscovering(false); await load(); };
  const apply=async(part:ApplyPart)=>{ if(!latest)return; setBusy(part); setError(""); setNotice(""); const body={action:"apply",enrichmentId:latest.id,applyDescription:part==="description",applyShortDescription:part==="shortDescription",applyAttributes:part==="attributes"}; const r=await fetch(`/api/admin/products/${productId}/catalog-enrichment`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}); const b=await r.json(); if(!r.ok)setError(b.error||"Erro"); else { const protectedCount=(b.protected?.attributeKeys?.length||0)+(b.protected?.description?1:0)+(b.protected?.shortDescription?1:0); setNotice(protectedCount?"Aplicado apenas onde não existiam alterações manuais. O conteúdo manual foi preservado.":"Conteúdo aplicado com sucesso."); await load(); await onChanged?.();} setBusy(null); };
  return <div className="space-y-4">
    <div className="rounded-lg border border-sky-200 bg-sky-50 p-3 text-xs text-sky-900"><b>S35.4 — Enriquecimento multi-fonte com identidade reforçada.</b> Esta área é independente dos TXT de pricelist e stock. ProductID/EAN/MPN são usados apenas para identificação/validação; preço, custo, margem, stock, nome, categorias ALSO e GPSR não são alterados aqui.</div>
    <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">Conteúdo já existente ou alterado manualmente é protegido. Uma nova versão do catálogo só substitui conteúdo anteriormente aplicado pela própria integração e que não tenha sido entretanto editado.</div>
    {error && <div className="rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    {notice && <div className="rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-700">{notice}</div>}
    <div className="border rounded-lg p-4"><h4 className="font-medium text-sm mb-2">Referências disponíveis</h4>{data?.links?.length ? data.links.map((l:any)=><div key={l.supplierId} className="text-xs text-slate-600">Fornecedor #{l.supplierId} · ProductID <b>{l.supplierSku||"—"}</b>{l.manufacturerPartNumber?` · MPN ${l.manufacturerPartNumber}`:""}</div>) : <p className="text-xs text-slate-500">Sem associação produto-fornecedor com ProductID.</p>}</div>
    <div className="border rounded-lg p-4"><div className="flex items-center justify-between gap-3"><div><h4 className="font-medium text-sm">Pesquisa automática</h4><p className="text-xs text-slate-500 mt-1">Executa um lote conservador de até 10 produtos do mesmo fornecedor. Primeiro tenta EAN exato. Se não existir correspondência, pode usar fabricante + MPN, mas só aceita uma correspondência única e exata; resultados ficam em snapshot e não são publicados automaticamente.</p></div><button type="button" disabled={discovering||!data?.links?.length} onClick={discover} className="px-3 py-2 rounded bg-indigo-600 text-white text-xs disabled:opacity-50">{discovering?"A pesquisar…":"Pesquisar 10 produtos"}</button></div></div>
    {!latest ? <div className="border rounded-lg p-4 text-sm text-slate-600"><p className="font-medium">Ainda não existe snapshot de conteúdo.</p><p className="text-xs mt-2">Ainda não existe snapshot para este produto. A pesquisa automática usa providers independentes e só aceita identidade validada; UPCitemdb por EAN exato ou, como fallback controlado, fabricante + MPN exatos. Não é feito scraping autenticado da loja ALSO.</p></div> : <div className="border rounded-lg p-4 space-y-4"><div><h4 className="font-medium text-sm">Pré-visualização #{latest.id}</h4><p className="text-xs text-slate-500">ProductID {latest.supplierSku} · {latest.provider}</p></div>
      <div><div className="flex items-center justify-between gap-3"><p className="text-xs font-medium text-slate-500">Descrição curta</p><button type="button" disabled={busy!==null} onClick={()=>apply("shortDescription")} className="px-3 py-1.5 rounded bg-sky-600 text-white text-xs disabled:opacity-50">{busy==="shortDescription"?"A aplicar…":"Aplicar descrição curta"}</button></div><p className="text-sm whitespace-pre-wrap mt-2">{latest.sourceShortDescription||"—"}</p></div>
      <div><div className="flex items-center justify-between gap-3"><p className="text-xs font-medium text-slate-500">Descrição</p><button type="button" disabled={busy!==null} onClick={()=>apply("description")} className="px-3 py-1.5 rounded bg-sky-600 text-white text-xs disabled:opacity-50">{busy==="description"?"A aplicar…":"Aplicar descrição"}</button></div><p className="text-sm whitespace-pre-wrap mt-2">{latest.sourceDescription||"—"}</p></div>
      <div><div className="flex items-center justify-between gap-3"><p className="text-xs font-medium text-slate-500">Especificações</p><button type="button" disabled={busy!==null} onClick={()=>apply("attributes")} className="px-3 py-1.5 rounded bg-sky-600 text-white text-xs disabled:opacity-50">{busy==="attributes"?"A aplicar…":"Aplicar especificações"}</button></div><pre className="text-xs bg-slate-50 rounded p-2 overflow-auto mt-2">{JSON.stringify(latest.sourceAttributes||{},null,2)}</pre></div>
      <p className="text-xs text-slate-500">Imagens candidatas: {(latest.sourceImages||[]).length}. A importação para R2 será feita pelo adaptador oficial, mantendo imagens manuais protegidas.</p></div>}
  </div>;
}
